name: Squash & release

on:
  push:
    branches: [master]

permissions: write-all

jobs:
  upload-resource-pack:
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install zip
        run: sudo apt-get update && sudo apt-get -y install zip

      - name: Zip contents of repository
        run: |
          zip -r Redemption-v${{ github.run_number }}.zip assets/ credits.txt pack.mcmeta pack.png 

      - name: Tag and create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ResourcePack-v${{ github.run_number }}
          files: Redemption-v${{ github.run_number }}.zip

      - name: Send Discord webhook
        uses: MineBartekSA/discord-webhook@v2.1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: '${{ github.actor }} published a new resourcepack on Github Releases: https://github.com/${{ github.repository }}/releases/download/ResourcePack-v${{ github.run_number }}/Redemption-v${{ github.run_number }}.zip\nChanges: ${{ github.event.head_commit.message }}'
          username: "Resource pack"
